### ISSUE TITLE
docker build fails on radare2 build

### ISSUE THREAD

**Issue by matthew-l-weber** [elisa-tech/ks-nav#21] opened 2024-01-09 15:07 UTC
Fresh clone of 57bdaa43733fec6afdb617a41048833aa94fd0f2

```
cd container
docker build -t ks-nav .
```

![image](https://github.com/elisa-tech/ks-nav/assets/1114905/5c9a3a6b-735b-435d-90d1-7a53abd140c9)

**Comment by matthew-l-weber** [comment] 2024-01-09 15:26
Feels like something on the toolchain build dependencies moved forward (changed architecture include definitions) and radare2 needs bump/integrated to a newer hash from "Jul 19, 2022 ".

**Comment by alessandrocarminati** [comment] 2024-04-04 07:31
As a preface, please accept my apologies for the delayed response to this issue.

I need to investigate why GitHub is not notifying me of new issues on this repository. 

Continuing on this topic, I have identified the problem:

`Radare2` is a rapidly evolving software. 
The maintainer commits changes on a daily basis, and not always is the `HEAD` working properly. 
I have encountered several issues while using a version that is not functioning correctly.

All of this is to say that the `Radare2` version I have pinned is becoming outdated, and one of its dependencies, capstone, has undergone some internal changes.

I am planning to update the `Radare2` version so that this problem can be mitigated.

**Comment by alessandrocarminati** [comment] 2024-04-04 11:21
Upon reviewing the problem, it appears that the failure to build the container stems from changes in the "capstone" dependency of Radare2, as anticipated. Additionally, the recent cgo builds seem to rely on specific dependencies with glibc, making the Alpine base incompatible with the project.

I've just pushed some changes that should restore the functionality. However, I'm not a container expert, but I recognize that this Dockerfile may be fragile. 
Heavy rework might be needed in the not-so-distant future to address these issues more comprehensively. 
Please close the issue if this change solves the problem for you.

**Comment by matthew-l-weber** [comment] 2024-04-04 20:49
fyi @dnjean

**Comment by alessandrocarminati** [comment] 2024-04-06 17:17
Thank you for confirming that this has resolved the issue.

The container provided here serves more as a demonstration than a fully-fledged application. Please note that there isn't a lighter version of ks-nav available, it is just that the container doesn't install all dependencies, for example to handle images from architectures different from the native one.

Assuming it's built on an x86_64 machine, you'll be able to collect symbols from an x86_64-built kernel.

The minimal web interface exposed by the container should allow you to scan an image in the kernel build directory you've mounted simply by clicking on the `acquire` button.

If you wish to explore the command-line tool, there are essentially two commands you can choose from:

* `nav-db-filler`, essentially `kern_bin_db`, is meant to be invoked in the root of the Linux build directory and should proceed by collecting all symbols. It provides nice progress bars during the process.
* `nav` is the other tool that queries the database and produces diagrams.

Feel free to reach out if you need further clarification or assistance.

**Comment by dnjean** [comment] 2024-04-09 10:41
I have the latest container also running and am trying to get the nav-db-filler command to run (via the cli first), but am not able to get past the nav-db-filler command. 

So far, I have: 
- created a conf.json which is like the out-of-the-box setup - and moved it in the same folder as my linux kernel source folder
![image](https://github.com/elisa-tech/ks-nav/assets/166069038/6d5829a5-13ec-4e8c-b5eb-54019cc9fbac)
- compiled a basic linux kernel from source - it creates a vmlinux image
- made sure the vmlinux image created is in the same folder as the Makefile in the linux kernel source folder 
- confirmed the path to strip and autoconf
- assumed that the DBDriver and DBDSN can both be used as-is (so I made no changes to that section of the conf.json)

To run the container, I run the following commands
- podman build -t ks-nav .
- podman run -it -p 5432:5432 -p 8080:8080 -v <path_to_my_linux_source>:/app localhost/ks-nav:latest 

Once in the container, I cd into the /app/linux folder and run: 
>> nav_db_filler -f <the_config.json_file_displayed above>

I am able to see the vmlinux.work generated, but I can't get past the database parsing - from reading about this type of errors, it may be caused by a potential go update (related to the delve module?)
 
Any hints on how to proceed from this point will be much appreciated.
![image](https://github.com/elisa-tech/ks-nav/assets/166069038/e342b826-d13d-45ea-aa4a-e465abc7b0dd)

**Comment by alessandrocarminati** [comment] 2024-04-12 11:14
Thank you for reaching out,

The container is designed to fulfill dependencies for a demo, which aligns with its primary purpose. 
Utilizing standalone applications within the container should also be straightforward.
Considering your description, it seems the container should already come configured with parameters suitable for both the demo and standalone usage. 
These parameters include:
* Utilizing the container-provided PostgreSQL service.
* Employing **native** bin-utils.
* Using a default note.

However, if you're inquiring, it suggests that the setup might not be as expected. 
In that case, the only parameters that might need adjustment are the ones described above.
The other parameters appearing in a config, define where to fetch data, which typically mirror the default locations of pertinent files within a kernel build directory, you should not need to change them. FYI, the mode one is a bitfield, and it is used for debug. Each field activates a specific section in the process of collecting data.

The configuration image you referenced appears to be an example included in the repository, which may not function unless you're within my home lab environment. The default configuration, as outlined here, assumes the PostgreSQL destination runs on the same host, and it is the one that this demo should use.

After building, the container should run smoothly with the following command:

```
podman run -it -p 5432:5432 -p 8080:8080 -v <Linux Build Directory>:/app -v <directory where PSQL data is stored>:/var/lib/pgsql/data localhost/ks-nav:latest
```

Regarding the hang you're experiencing, it's likely due to an attempt to contact `dbs.hqhome163.com`, which is a host within my home lab network and is unreachable from outside.

I hope this information proves helpful. 
Feel free to reach out if you need further assistance, and I'll endeavor to respond promptly.

**Comment by alessandrocarminati** [comment] 2024-04-12 11:41
I'm going to close this issue since its primary objective seem to have been reached.
Feel free to open a new issue if anything else is needed.

**Closed by alessandrocarminati** 2024-04-12 11:41 UTC
Labels: bug
